### ISSUE TITLE
Модуль BatteryPilling не работает

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/home-automation#207]
[2015-02-02 15:51:04.237] [I] [core] Notification: error (core): Can not instantiate module BatteryPolling: TypeError: undefined is not a function
[2015-02-02 15:51:04.261] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:258:24)
    at AutomationController.reconfigureInstance (automation/classes/AutomationController.js:477:22)
    at ZAutomationAPIWebRequest.<anonymous> (automation/webserver.js:605:44)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/request.js:246:30)
    at automation/request.js:32:35
    at WebServerRequestHandler (automation/main.js:85:10)

**Comment by PoltoS** [comment]
https://github.com/Z-Wave-Me/home-automation/issues/208
