### ISSUE TITLE
Модуль SensorsPolling не работает

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/home-automation#208]
[2015-02-02 16:01:28.238] [I] [core] Notification: error (core): Can not instantiate module SensorsPolling: TypeError: undefined is not a function
[2015-02-02 16:01:28.260] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:258:24)
    at AutomationController.reconfigureInstance (automation/classes/AutomationController.js:477:22)
    at ZAutomationAPIWebRequest.<anonymous> (automation/webserver.js:605:44)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/request.js:246:30)
    at automation/request.js:32:35
    at WebServerRequestHandler (automation/main.js:85:10)

**Comment by PoltoS** [comment]
а ты бы читал логи ;) Cron добавить сначала надо. Вообще, он не должен был даже начать запускаться....
