### ISSUE TITLE
SecurityMode error

### ISSUE THREAD

**Issue by jhmartin** [Z-Wave-Me/home-automation#236]
I get an error trying to instantiate SecurityMode:
```
[2015-04-16 20:43:14.047] [I] [core] Instantiating module 9 from class SecurityMode
[2015-04-16 20:43:14.311] [I] [core] --- Starting module Security mode
[2015-04-16 20:43:14.347] [I] [core] Notification: error (core): Can not init module SecurityMode: TypeError: Cannot read property 'deviceType' of undefined
[2015-04-16 20:43:14.375] [I] [core] TypeError: Cannot read property 'deviceType' of undefined
    at _.extend.create (automation/classes/DevicesCollection.js:44:58)
    at SecurityMode.init (automation/modules/SecurityMode/index.js:44:41)
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:227:22)
    at AutomationController.reconfigureInstance (automation/classes/AutomationController.js:417:22)
    at ZAutomationAPIWebRequest.<anonymous> (automation/webserver.js:606:44)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/request.js:251:30)
    at automation/request.js:31:35
    at WebServerRequestHandler (automation/main.js:85:10)
```

The configuration is:
```json
   {
            "active": true,
            "description": "Security mode allows to trigger scenes based on devices status.",
            "id": 9,
            "moduleId": "SecurityMode",
            "params": {
                "action": {
                    "dimmers": [],
                    "locks": [],
                    "message": "Alert!",
                    "scenes": [],
                    "switches": [
                        {
                            "device": "ZWayVDev_zway_15-0-37",
                            "status": "on"
                        }
                    ]
                },
                "tests": [
                    {
                        "testBinary": {
                            "device": "ZWayVDev_zway_17-0-48-1",
                            "testValue": "on"
                        },
                        "testType": "binary"
                    }
                ]
            },
            "title": "Security mode"
        }
```

**Comment by aivs** [comment]
Check that the sensors that you use in the module exists

**Comment by jhmartin** [comment]
I recreated the SecurityMode portion several times, and I see both mentioned devices in config.json:
```json
        "ZWayVDev_zway_17-0-48-1": {
            "deviceType": "sensorBinary",
            "location": null,
            "metrics": {
                "icon": "motion",
                "level": "off",
                "probeTitle": "General purpose",
                "scaleTitle": "",
                "title": "Back door"
            },
            "permanently_hidden": false,
            "tags": []
        }
```

and
```json
        "ZWayVDev_zway_15-0-37": {
            "deviceType": "switchBinary",
            "location": null,
            "metrics": {
                "icon": "switch",
                "level": "off",
                "title": "Backyard Light"
            },
            "permanently_hidden": false,
            "tags": []
        }
```

**Comment by PoltoS** [comment]
still not fixed?
