### ISSUE TITLE
Can't start automation. Start error: "Cannot read property 'filter' of undefined"

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/home-automation#258]
[2015-07-20 13:21:50.775] [E] [core] result: Error: TypeError: Cannot read property 'filter' of undefined
    at AutomationController.loadModule (automation/classes/AutomationController.js:389:19)
    at AutomationController.<anonymous> (automation/classes/AutomationController.js:409:14)
    at Array.forEach (native)
    at AutomationController.instantiateModules (automation/classes/AutomationController.js:408:46)
    at AutomationController.start (automation/classes/AutomationController.js:147:10)
    at automation/main.js:303:16

**Comment by Vebryn** [comment]
I agree with aivs, I encount the same issue with latest version available : z-way-server-RaspberryPiXTools-v2.1.2-rc2

[2015-05-01 00:29:23.077] [I] [core] Executing script: /*** Z-Way Home Automation Engine main executable ***************************** ...
[2015-05-01 00:29:23.082] [I] [core] Executing script: // Comon utilities and functions ...
[2015-05-01 00:29:23.111] [I] [core] Executing script: // This script transforms old formats to new ...
[2015-05-01 00:29:23.133] [I] [core] Executing script: /*! ...
[2015-05-01 00:29:23.272] [I] [core] Executing script: //     Underscore.js 1.7.0 ...
[2015-05-01 00:29:23.417] [I] [core] Executing script: /*** Z-Way HA Virtual Device base class *************************************** ...
[2015-05-01 00:29:23.435] [I] [core] Executing script: /*** Z-Way DevicesCollection class ************************************ ...
[2015-05-01 00:29:23.571] [I] [core] Executing script: /*** Z-Way HA Controller class module ***************************************** ...
[2015-05-01 00:29:23.594] [I] [core] Executing script: /*** Automation Webserver Auth Controller ************************************* ...
[2015-05-01 00:29:23.602] [I] [core] Executing script: /*** Z-Way HA Automation module base class ************************************ ...
[2015-05-01 00:29:23.608] [I] [core] Executing script:  ...
[2015-05-01 00:29:23.626] [I] [core] Executing script: /*** Main Automation storage module ***************************************** ...
[2015-05-01 00:29:23.656] [I] [core] Executing script: /*** Main Automation webserver module ***************************************** ...
[2015-05-01 00:29:23.662] [I] [core] Executing script: // Make this testable by pulling in underscore from the parent module ...
[2015-05-01 00:29:23.674] [I] [core] Executing script: /*** Main Automation storage module ***************************************** ...
[2015-05-01 00:29:23.725] [I] [core] --- Loading ZAutomation classes
[2015-05-01 00:29:23.972] [I] [core] Starting ZWay Automation webserver
[2015-05-01 00:29:23.989] [I] [core] Loading modules...
[2015-05-01 00:29:24.017] [I] [core] Loading module SecurityMode from modules/SecurityMode
[2015-05-01 00:29:24.023] [I] [core] Executing script: /*** SecurityMode Z-Way HA module ******************************************* ...
[2015-05-01 00:29:24.124] [E] [core] result: Error: TypeError: Cannot read property 'filter' of undefined
    at AutomationController.loadModule (automation/classes/AutomationController.js:397:19)
    at AutomationController.<anonymous> (automation/classes/AutomationController.js:439:14)
    at Array.forEach (native)
    at AutomationController.instantiateModules (automation/classes/AutomationController.js:438:46)
    at AutomationController.start (automation/classes/AutomationController.js:154:10)
    at automation/main.js:90:16

**Comment by aivs** [comment]
The problem is that you deleted config.json
Сonfig.json is not created automatically, you have to copy it from a previous installation.

**Comment by Vebryn** [comment]
Thank you for your answer.
It's a fresh installation. I'm going to try tomorrow, may be taking one from previous version.

**Comment by Vebryn** [comment]
I copy config.json_ttyAMA0 from defaultConfigs dir to z-way-server/automation/config.json. Same error appears. Where have I to put config.json file ? Is defaultConfigs dir containing ready to use files ?

**Comment by aivs** [comment]
File name should be:
configjson-06b2d3b23dce96e1619d2b53d6c947ec.json

And placed in:
/opt/z-way-server/automation/storage

**Comment by Vebryn** [comment]
Problem solved, version 2.1.1 is working fine with some prerequisites:
* libarchive12 (only available from wheezy raspbian)
* libxml2

Z-Way-Server is working fine after installing these dependencies. New GUI accessed by 8083 port is nice.
