### ISSUE TITLE
 Cannot instantiate module: HomeKitGate: Error: Invlid type UUID

### ISSUE THREAD

**Issue by potuijt** [Z-Wave-Me/home-automation#296]
Getting this error when activated Homekit and restart the system..

**Comment by Rubicoin** [comment]
Same here :(

**Comment by Rubicoin** [comment]
Same here :(

I removed the old home kit gate, rebooted the system and added it again, I got this:

```[2015-12-01 19:05:22.269] [I] [core] Instantiating module 10 from class HomeKitGate
[2015-12-01 19:05:22.282] [I] [core] --- Starting module Apple HomeKit Gate
[2015-12-01 19:05:22.350] [I] [core] Notification: error (core): Cannot instantiate module: HomeKitGate: Error: Invlid type UUID
[2015-12-01 19:05:22.361] [I] [core] Error: Invlid type UUID
    at new HKCharacteristic (zway/homekit:453:15)
    at HKService.addCharacteristic (zway/homekit:426:26)
    at onDeviceAddedCore (automation/modules/HomeKitGate/index.js:260:24)
    at Function._.each._.forEach (automation/lib/underscore.js:146:17)
    at _.extend.each (automation/classes/DevicesCollection.js:181:18)
    at HomeKitGate.init (automation/modules/HomeKitGate/index.js:502:26)
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:313:22)
    at AutomationController.reconfigureInstance (automation/classes/AutomationController.js:686:22)
    at ZAutomationAPIWebRequest._.extend.reconfigureInstanceFunc (automation/ZAutomationAPIProvider.js:1097:40)
    at ZAutomationAPIWebRequest.handlerFunc (automation/ZAutomationAPIProvider.js:1777:52)```

If I try to remove it and add it again I got:

```
[2015-12-02 09:09:35.752] [I] [core] Instantiating module 13 from class HomeKitGate
[2015-12-02 09:09:35.756] [I] [core] WARNING: Module 13 is a singleton and already has been instantiated. Skipping.
```

**Comment by holgicgn** [comment]
Same here too (RaZberry Version 2.1.2-rc17)

[2015-12-01 19:05:22.269] [I] [core] Instantiating module 10 from class HomeKitGate
[2015-12-01 19:05:22.282] [I] [core] --- Starting module Apple HomeKit Gate
[2015-12-01 19:05:22.350] [I] [core] Notification: error (core): Cannot instantiate module: HomeKitGate: Error: Invlid type UUID
[2015-12-01 19:05:22.361] [I] [core] Error: Invlid type UUID
    at new HKCharacteristic (zway/homekit:453:15)
    at HKService.addCharacteristic (zway/homekit:426:26)
    at onDeviceAddedCore (automation/modules/HomeKitGate/index.js:260:24)
    at Function._.each._.forEach (automation/lib/underscore.js:146:17)
    at _.extend.each (automation/classes/DevicesCollection.js:181:18)
    at HomeKitGate.init (automation/modules/HomeKitGate/index.js:502:26)
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:313:22)
    at AutomationController.reconfigureInstance (automation/classes/AutomationController.js:686:22)
    at ZAutomationAPIWebRequest._.extend.reconfigureInstanceFunc (automation/ZAutomationAPIProvider.js:1097:40)
    at ZAutomationAPIWebRequest.handlerFunc (automation/ZAutomationAPIProvider.js:1777:52)

**Comment by PoltoS** [comment]
HK module is deprecated
