### ISSUE TITLE
Password Recovery Error

### ISSUE THREAD

**Issue by islipfd19** [Z-Wave-Me/home-automation#312]
I find the below error in my z-way-server log when testing the 'password recovery' feature at the login prompt. Sendmail is installed and setup correctly, my raspberry is capable of sending emails without issue. The message "SmartHome UI Internal server error" is displayed on the UI.

(Email below has been masked)

[2015-12-23 21:15:07.067] [I] [core] Tokenrequest already exists for e-mail: XXXXXXX@gmail.com
[2015-12-23 21:15:15.522] [E] [8083] Callback execution error: TypeError: Cannot read property 'call' of undefined
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:40)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:29:11)

**Comment by PoltoS** [comment]
Seems fixed. Please confirm

**Comment by islipfd19** [comment]
Working as expected
