### ISSUE TITLE
After upgrade from v2.1.1 to v2.2.3 Scheduled Scenes are failing

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/home-automation#365]
After this upgrade all my active scheduledScenes are failing. The log says the following:

[2016-07-16 09:30:00.635] [E] [core] Callback execution error: TypeError: Cannot read property 'forEach' of undefined
    at AutomationController.runScene (automation/modules/ScheduledScene/index.js:59:26)
    at AutomationController.EventEmitter.emit (automation/lib/eventemitter2.js:317:33)
    at automation/modules/Cron/index.js:133:42
    at Array.forEach (native)
    at automation/modules/Cron/index.js:121:27
    at Array.forEach (native)
    at Function.<anonymous> (automation/modules/Cron/index.js:118:37)
[2016-07-16 09:30:26.911] [D] [zway] RECEIVED: ( 01 08 00 04 00 21 02 84 07 53 )
[2016-07-16 09:30:26.912] [D] [zway] SENT ACK

I haven't observed this in the past, but I did observe [something similar after a restore issue#282](https://github.com/Z-Wave-Me/home-automation/issues/282)

**Comment by PoltoS** [comment]
Please try this fix a9ec9de. Have not tested it, but should work.

**Comment by pz1** [comment]
thanks; Have updated the code, restarted ZWay. Will check later tonight or tomorrow if it works.

**Comment by pz1** [comment]
Well, the ScheduledScene for 22:30 was executed correctly. I assume the rest will work too.

So, as far as I am concerned this Issue may be closed

**Comment by PoltoS** [comment]
Thanks for confirmation!
