### ISSUE TITLE
Second Z-Wave module not generate a widgets

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/home-automation#369]
I added second Z-Wave module with name zwayUSB0, after start in log errors:
```
[2016-07-27 02:51:19.948] [D] [zwayUSB0] RECEIVED: ( 01 04 01 54 00 AE )
[2016-07-27 02:51:19.948] [D] [zwayUSB0] SENT ACK
[2016-07-27 02:51:19.948] [I] [zwayUSB0] Job 0x54 (Set new SUC/SIS): Failed
[2016-07-27 02:51:19.948] [D] [zwayUSB0] Job 0x54 (Set new SUC/SIS): fail
[2016-07-27 02:51:19.948] [I] [zwayUSB0] Removing job: Set new SUC/SIS
[2016-07-27 02:51:19.989] [I] [core] Creating device battery ZWayVDev_zwayUSB0_2-0-128
[2016-07-27 02:51:20.029] [E] [core] Callback execution error: TypeError: Cannot read property 'data' of undefined
    at ZDataHolder.<anonymous> (automation/modules/ZWave/index.js:1255:40)
    at ZWave.dataBind (automation/modules/ZWave/index.js:1135:10)
    at ZWaveCommandClass.<anonymous> (automation/modules/ZWave/index.js:1250:9)
[2016-07-27 02:51:20.030] [E] [core] Callback execution error: TypeError: Cannot read property 'data' of undefined
    at ZDataHolder.<anonymous> (automation/modules/ZWave/index.js:1255:40)
    at ZWave.dataBind (automation/modules/ZWave/index.js:1135:10)
    at ZWaveCommandClass.<anonymous> (automation/modules/ZWave/index.js:1250:9)
```

It happens because in ZWave module used local self.zway instead global zway.

**Comment by ronie-z-wave** [comment]
hmm ok, so it needs
 to be change in self.zway, right?

**Comment by PoltoS** [comment]
@ronie-z-wave yes, because zway is a global var, while self.zway is the zway instance related to this particular module Z-Wave binding,

**Comment by ronie-z-wave** [comment]
Indeed. Done. Please test it :)
