### ISSUE TITLE
Sonos module: sockets is not defined

### ISSUE THREAD

**Issue by Scapal** [Z-Wave-Me/home-automation#405]
Running the latest released firmware v2.2.5, UI 1.5.0 

```
[2016-12-23 09:52:55.196] [I] [core] --- Starting module Sonos
[2016-12-23 09:52:55.222] [I] [core] Notification: error (core): Cannot instantiate module: Sonos: ReferenceError: sockets is not defined
[2016-12-23 09:52:55.258] [I] [core] ReferenceError: sockets is not defined
```

**Comment by PoltoS** [comment]
Which OS? looks you don't have some lib. Please try to run it from the console and look on output. It will compain

**Comment by Scapal** [comment]
RaZberry sd image from http://razberry.z-wave.me/index.php?id=24

**Comment by Scapal** [comment]
`Failed to load module modsockets.so: libcares.so.2: cannot open shared object file: No such file or directory`

**Comment by PoltoS** [comment]
oh... please do
sudo apt-get install libc-ares2

Does it help?

**Comment by Scapal** [comment]
Yes it fixed it.
There is still a problem setting the household, the detection works but there seems to be a problem saving it:
```
[2016-12-23 21:10:48.353] [I] [core] Detected Sonos Household: Sonos_W<removed>F
[2016-12-23 21:10:48.378] [E] [core] Callback execution error: TypeError: Cannot set property 'params' of undefined
    at Sonos.AutomationModule.saveConfig (automation/classes/AutomationModule.js:77:45)
    at udp.sockHouseholdFinder.onrecv (automation/modules/Sonos/index.js:99:18)
```

If I copy/paste the household in the Sonos app config, it works.

**Comment by PoltoS** [comment]
that shounds strange, this method works in general. Will test that once I have access to Sonos again.

**Comment by PoltoS** [comment]
Have you tried to remove the app and add it again?
