### ISSUE TITLE
Sonos Module - Windows

### ISSUE THREAD

**Issue by Isaksson** [Z-Wave-Me/home-automation#408]
Hello.
I have been running this module on my RPI and Razberry but now my Razberry broke for some reason and now i am trying to run this on the Windows build 2.2.4.

I can't get the module to start. Here is the error message from the log file.

[2017-01-01 21:25:01.295] [I] [core] Instantiating module 10 from class Sonos
[2017-01-01 21:25:01.295] [I] [core] --- Starting module Sonos
[2017-01-01 21:25:01.298] [I] [core] Notification: error (core): Cannot instantiate module: Sonos: Error: No such file or directory
[2017-01-01 21:25:01.303] [I] [core] Error: No such file or directory
    at Error (native)
    at Sonos.householdFinder (automation/modules/Sonos/index.js:84:25)
    at Sonos.init (automation/modules/Sonos/index.js:44:10)
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:445:22)
    at AutomationController.createInstance (automation/classes/AutomationController.js:877:23)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1055:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:259:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:29:11)

**Comment by PoltoS** [comment]
Please check the line 84 in automation/modules/Sonos/index.js. Looks it is `sockHouseholdFinder.bind("255.255.255.255", 6969);`. If so, looks broadcast on Windows should work a bit different. Or it is .reusable()?

**Comment by PoltoS** [comment]
BTW, commenting this should work if you have the household already detected.

**Comment by Isaksson** [comment]
Yes, it is the HouseholdFinder that is the problem here, i comment out this.householdFinder(); in the Init function and also this.sockHouseholdFinder && this.sockHouseholdFinder.close(); and this.sockHouseholdFinder = null; in the stop function.

Now he creates the virtual devices but not receiving any updates from the sonos system, cant tell if device is playing or not and the volume just says NaN, But i could start and stop Sonos devices with the virtual buttons

`[2017-01-02 12:28:51.245] [I] [core] Instantiating module 10 from class Sonos
[2017-01-02 12:28:51.246] [I] [core] --- Starting module Sonos
[2017-01-02 12:28:51.254] [I] [core] Binding Sonos notifier
[2017-01-02 12:28:51.355] [I] [core] Detected AV capable Sonos player on 10.0.20.27
[2017-01-02 12:28:51.356] [I] [core] Creating device switchBinary Sonos_Device_Play_10.0.20.27_10
[2017-01-02 12:28:51.364] [I] [core] Creating device switchMultilevel Sonos_Device_Volume_10.0.20.27_10
[2017-01-02 12:28:51.642] [I] [core] Detected AV capable Sonos player on 10.0.20.29
[2017-01-02 12:28:51.643] [I] [core] Creating device switchBinary Sonos_Device_Play_10.0.20.29_10
[2017-01-02 12:28:51.645] [I] [core] Creating device switchMultilevel Sonos_Device_Volume_10.0.20.29_10
[2017-01-02 12:28:51.670] [I] [core] Detected AV capable Sonos player on 10.0.20.26
[2017-01-02 12:28:51.671] [I] [core] Creating device switchBinary Sonos_Device_Play_10.0.20.26_10
[2017-01-02 12:28:51.672] [I] [core] Creating device switchMultilevel Sonos_Device_Volume_10.0.20.26_10
[2017-01-02 12:28:51.711] [I] [core] Detected AV capable Sonos player on 10.0.20.30
[2017-01-02 12:28:51.711] [I] [core] Creating device switchBinary Sonos_Device_Play_10.0.20.30_10
[2017-01-02 12:28:51.712] [I] [core] Creating device switchMultilevel Sonos_Device_Volume_10.0.20.30_10
[2017-01-02 12:28:51.776] [I] [core] Detected AV capable Sonos player on 10.0.20.28
[2017-01-02 12:28:51.776] [I] [core] Creating device switchBinary Sonos_Device_Play_10.0.20.28_10
[2017-01-02 12:28:51.779] [I] [core] Creating device switchMultilevel Sonos_Device_Volume_10.0.20.28_10
[2017-01-02 12:28:52.027] [I] [core] Detected AV capable Sonos player on 10.0.20.25
[2017-01-02 12:28:52.027] [I] [core] Creating device switchBinary Sonos_Device_Play_10.0.20.25_10
[2017-01-02 12:28:52.028] [I] [core] Creating device switchMultilevel Sonos_Device_Volume_10.0.20.25_10
[2017-01-02 12:30:08.508] [I] [core] ---  Sonos_Device_Play_10.0.20.30_10 performCommand processing: {"0":"on","1":{}}
[2017-01-02 12:30:24.169] [I] [core] ---  Sonos_Device_Play_10.0.20.30_10 performCommand processing: {"0":"off","1":{}}
[2017-01-02 12:30:45.787] [I] [core] ---  Sonos_Device_Play_10.0.20.30_10 performCommand processing: {"0":"off","1":{}}
[2017-01-02 12:30:54.106] [I] [core] ---  Sonos_Device_Play_10.0.20.30_10 performCommand processing: {"0":"on","1":{}}
`

**Comment by PoltoS** [comment]
Hm.. subscriptions are made by Sonos.prototype.subscribe while notifications falls in Sonos.prototype.notifier (sockNotifier.onrecv). Please put a `console.log(this.msg);` after `this.msg = ...` to see if notifications arrive

**Comment by Isaksson** [comment]
I have now made some tests with console.log no notifications does arrive so I made a test like this

`var sockNotifier = new sockets.tcp();
    sockNotifier.reusable();
    sockNotifier.bind(3400);
	console.log('bind against 3400');
    sockNotifier.onconnect = function(host, port) {
        this.msg = "";
		console.log('onConnect');
    };`

And i receive "bind against 3400" in the log but "onConnect" never fires, and i guess that explains why no updates is received.

Any ideas whats going on here?

**Comment by PoltoS** [comment]
Use tcpdump to see if notification arrives from Sonos. May be they don't?

If they dont, then check the part wit subscribe - may be something is wrong there?

**Comment by Isaksson** [comment]
I will run some more tests, by the way, is it possible to reload modified files (Sonos Module index.js in this case) without to restart the z-way service?

**Comment by ronie-z-wave** [comment]
Hi, 

Yes. Please try `http://YOUR_BOX:8083/ZAutomation/api/v1/modules/reinitialize/Sonos`

**Comment by Isaksson** [comment]
Thanks, that is much better that restart the service :)
I could not see any notifications, I have not managed yet to find a solution for this.
If anyone have any ideas just share them and maybe we could solve this together

But it does not feel good that some modules does work on linux but not on windows.
The two modules that I need to have MQTT and Sonos does not work on Windows.

**Comment by Isaksson** [comment]
I have now verified same errors on another Windows installation just to be sure this was not just a problem on one installation.

**Comment by PoltoS** [comment]
Do you have a Pi to test it on Linux? Just to make sure it is a module problem and not your houseHold specific problem.

Please put a console.log here: https://github.com/Z-Wave-Me/home-automation/blob/master/modules/Sonos/index.js#L249
to make sure the connection establishes. Also try to tcpdump this connection to make sure subscription was correct. I see few possible reasons:
1. For some reason the connection is not established
2. The format of subscription is wrong for your Sonos (sniff you mobile app to compare)
3. Sonos is not sendig updates at all (very unlikely)

**Comment by Isaksson** [comment]
I will test the console.log on that row.

Yes the module is working on the Pi, I have used this from day one when you created this module, but my razberry card broke and then i moved over to windows.
And that is when I noticed this problem and posted here about them.

**Comment by PoltoS** [comment]
May be a short online debugging via TeamViewer? ;) But first please check the suggestions above

**Comment by Isaksson** [comment]
I have now tried the console.log and it never hits.
I fired up my old razberry development pi and Sonos module worked as it should on that.

I tried to install Ubuntu in a virtual environment on my Windows server but when i started the Sonos module there i get new error message saying:
Reference error: http is not defined.

Maybe I have to give up my idea to run this on my Windows server and get back to Rpi with multiply sd-card failures every year, and not a proper backup solution :(

And it seems that development on windows build is still behind on every version that is released.

**Comment by PoltoS** [comment]
> Reference error: http is not defined.
This means wrong libcurl is installed. Check on Z-Way start the console (not log) - it complains.

Indeed, Windows is not our primary, but strange it does not work...

So, this means connection is actually not established. Firewall? If socket is created, but connection do not happen, means:
1) connection error
2) onconnect comes after the connection has been created (may be it was too fast).

Simple wireshart should reveal it.

**Comment by Isaksson** [comment]
Iam now moving back to rpi, have installed the latest z-way there, but when i tried to take a backup from the windows version then i found out that that function seems broken (i have created new issue here about that) so I don't know how i should proceed with that.
Should we close this issue? or what do you think, the module is obvious broken on windows environment but there is lots of issue with the windows installation so i guess this is not the prioritised issue there.
