### ISSUE TITLE
"Cannot create vDev based on: 6-0-113: TypeError: Cannot read property 'forEach' of null" at zway-server start

### ISSUE THREAD

**Issue by pmbert** [Z-Wave-Me/home-automation#476]
Each time I restart z-way-server I'm getting this error message.
It's always the same device 6-0-113 (Tamper of an Aeotec Multisensor 6). And I don't use it. It is deactivated.

Corresponding log file entries:
[2018-11-11 13:34:42.234] [I] [core] Creating device sensorBinary ZWayVDev_zway_6-0-48-1
[2018-11-11 13:34:42.322] [I] [core] Notification: device-info (device-OnOff): {"dev":"ON-WZ Bewegung","l":"off","location":4}
[2018-11-11 13:34:42.428] [I] [core] Creating device sensorMultilevel ZWayVDev_zway_6-0-49-1
[2018-11-11 13:34:42.513] [I] [core] Notification: device-info (device-temperature): {"dev":"ON-WZ Temperatur","l":"19.9 °C","location":4}
[2018-11-11 13:34:42.619] [I] [core] Creating device sensorMultilevel ZWayVDev_zway_6-0-49-3
[2018-11-11 13:34:42.785] [I] [core] Creating device sensorMultilevel ZWayVDev_zway_6-0-49-5
[2018-11-11 13:34:42.892] [I] [core] Notification: device-info (device-humidity): {"dev":"ON-WZ Feuchtigkeit","l":"50 %","location":4}
[2018-11-11 13:34:42.975] [I] [core] Creating device sensorMultilevel ZWayVDev_zway_6-0-49-27
[2018-11-11 13:34:43.184] [I] [core] Creating device sensorBinary ZWayVDev_zway_6-0-113-7-3-A
[2018-11-11 13:34:43.389] [I] [core] Notification: error (core): Cannot create vDev based on: 6-0-113: TypeError: Cannot read property 'forEach' of null
[2018-11-11 13:34:43.403] [I] [core] TypeError: Cannot read property 'forEach' of null
    at maskArrayToTypes (automation/modules/ZWave/index.js:5405:21)
    at automation/modules/ZWave/index.js:5420:83
    at Array.forEach (native)
    at ZWave.parseAddCommandClass (automation/modules/ZWave/index.js:5393:25)
    at ZDataHolder.<anonymous> (automation/modules/ZWave/index.js:3989:12)
    at ZWave.dataBind (automation/modules/ZWave/index.js:3579:10)
    at ZWaveCommandClass.<anonymous> (automation/modules/ZWave/index.js:3696:9)
[2018-11-11 13:34:43.413] [I] [core] Creating device battery ZWayVDev_zway_6-0-128

My configuration:
Raspberry Pi 3 Model B Rev 1.2
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
Raspbian GNU/Linux 8
Z-Way version v2.3.7 from 2018-03-23 09:28:53 +0300 (build b1902d4433d1337bd488834db3347fa7ef8f8a33)

**Comment by PoltoS** [comment]
Lokks like interview failed on this device. Just skip it

**Comment by pmbert** [comment]
Interview is complete for this device. I can activate and I can deactivate it. And when it's activated, it works.

**Comment by PoltoS** [comment]
In that case show us the zway.devices[N].Alarm.data

**Comment by pmbert** [comment]
Is this the data you want?

CommandClass
/: None (21.12.2017)
    6: None (20.06.2018)
        typeString: Access Control (20.06.2018)
        status: 255 (20.06.2018)
        eventMask: None (20.06.2018)
        event: 23 (20.06.2018)
        eventString: Window/door is closed (20.06.2018)
        eventParameters:  (20.06.2018)
    7: None (10:30)
        typeString: Burglar (21.12.2017)
        status: 255 (10:30)
        eventMask: 8,1 (21.12.2017)
        event: 0 (10:30)
        eventString:  (10:30)
        eventParameters:  (10:30)
        eventSequence: None (10:25)
    supported: true (21.12.2017)
    version: 3 (21.12.2017)
    security: false (21.12.2017)
    interviewDone: true (21.12.2017)
    interviewCounter: 9 (21.12.2017)
    V1supported: false (21.12.2017)
    typeMask: 128 (21.12.2017)
    V1event: None (21.12.2017)
        alarmType: None (21.12.2017)
        level: None (21.12.2017)

**Comment by pmbert** [comment]
New information: I activated device Tamper (6.0.113.7.3) and restarted zway-server. Error message was coming again.
Now additionally there is another device Aeotec Burglar Alarm (#6). Both are working, when I'm touching the device.

{

    "creationTime": 1484597133,
    "creatorId": 1,
    "customIcons": { },
    "deviceType": "sensorBinary",
    "h": 1126350820,
    "hasHistory": false,
    "id": "ZWayVDev_zway_6-0-113-7-3-A",
    "location": 0,
    "metrics": {
        "icon": "smoke",
        "level": "on",
        "title": "Tamper (6.0.113.7.3)",
        "modificationTime": 1542103254,
        "lastLevel": "on",
        "isFailed": false
    },
    "order": {
        "rooms": 0,
        "elements": 0,
        "dashboard": 0
    },
    "permanently_hidden": false,
    "probeType": "alarm_burglar",
    "tags": [ ],
    "visibility": true,
    "updateTime": 1542103254

},

{

    "creationTime": 1541959108,
    "creatorId": 1,
    "customIcons": { },
    "deviceType": "sensorBinary",
    "h": 90683202,
    "hasHistory": false,
    "id": "ZWayVDev_zway_6-0-113-7-254-A",
    "location": 0,
    "metrics": {
        "icon": "alarm_burglar",
        "level": "off",
        "title": "Aeotec Burglar Alarm (#6)",
        "isFailed": false,
        "modificationTime": 1542101444,
        "lastLevel": "off"
    },
    "order": {
        "rooms": 0,
        "elements": 0,
        "dashboard": 0
    },
    "permanently_hidden": false,
    "probeType": "alarm_burglar",
    "tags": [ ],
    "visibility": true,
    "updateTime": 1542103175

}

**Comment by pmbert** [comment]
Now after another zway-server restart device ZWayVDev_zway_6-0-113-7-254-A is gone again. Only ZWayVDev_zway_6-0-113-7-3-A still exists. Device is still activated.

**Comment by pmbert** [comment]
Indeed after new interview the error message has gone.
The alarm data now are:

CommandClass
/: None (17:19)
    7: None (17:41)
        typeString: Burglar (17:19)
        status: 255 (17:41)
        eventMask: 8,1 (17:19)
        event: 8 (17:41)
        eventString: Motion detected, location unknown (17:41)
        eventParameters:  (17:41)
        eventSequence: None (17:41)
    supported: true (17:19)
    version: 3 (17:19)
    security: false (17:19)
    interviewDone: true (17:19)
    interviewCounter: 9 (17:19)
    V1supported: false (17:19)
    typeMask: 128 (17:19)
    V1event: None (17:19)
        alarmType: None (17:19)
        level: None (17:19)

The question arises where the wrong data came from.
